### ISSUE TITLE
Enemy Revamp Notes

### ISSUE THREAD

**Issue by Hashiane** [pibolib/hack16-2#5]
- Dictionary for default enemy values
- > HP
- > Score gain
- Enemy types (WIP)
- > Regular (rifle; single shots)
- > Assault (AR; burst shots)
- > Shotgunner (shotgun; spread shots)
- > Grounded enemies (mortars; single shot, explodes into shrapnel)
- > Stealth-type (snipers; straight line telegraphed shots)

**Comment by pibolib** [comment]
We're not going to add the grounded type enemies in this hackathon version. It's out of scope.
In the future, let's split up separate specifications into separate issues.
